[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#2C5F87"
backgroundColor = "#fffaf2"
secondaryBackgroundColor = "#f4ede0"
textColor = "#2A2825"
font = "serif"
